[project]
name = "judge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "psycopg[binary]>=3.2.13",
]

[project.scripts]
judge = "judge:main"

[build-system]
requires = ["uv_build>=0.12.24,<0.13.0"]
build-backend = "uv_build"
